courses/urls.py
from django.urls import path

from . import views

app_name="courses"
urlpatterns = [
 path('', views.course_list, name='list'),
 path('<int:course_pk>/<int:step_pk>/', views.step_detail, name='step_detail'),
 path('<int:pk>/', views.course_detail, name='course_detail'),

]

learning_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
    path ('courses/', include('courses.urls', namespace="courses"), name='courses'),
    path('admin/', admin.site.urls),
    path('', views.hello_world, name='home')

]
urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models

# Create your models here. 
# Model names should be singluar
class Course(models.Model):
    '''Class to create a course'''
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=50)
    description = models.TextField()


    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)
    content = models.TextField(blank=True, default='')

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.title

courses/views.py
from django.shortcuts import render, get_object_or_404


from . models import Course, Step
# Create your views here.

def course_list(request):
    courses = Course.objects.all()
    return render(request, 'courses/course_list.html', {'courses': courses})

def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk,pk=step_pk)
    return render(request, 'courses/step_detail.html',{'step':step})

learning_site/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% block title %} {{ course.title}}{% endblock title %}

{%block content%}
<article>
    <h2> {{course.title}}</h2>
    {{course.description}}
    <section>
        {% for step in couse.step_set.all %}
        <h3><a href="{% url 'step_detail' course+ ">{{step.title}}</a></h3>
            {{step.description}}
            {% endfor %}    
    </section>
</article>
{%endblock content%}

courses/templates/courses/course_list.html
{% extends "layout.html" %}

{%block title%} Available Courses{%endblock title%}

{% block content %}
<div class='cards'>
    {% for course in courses %}
    <div class="card">
        <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }} </a></header>
        <div class="card-copy"> 
            {{ course.description}}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock  %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% block title %} {{ step.course.title }} - {{ step.course.title }}{% endblock title %}
{% block content%}
<article> 
    <h2><a href="{% url 'detail' pk=step_course.pk%}">{{ step.course.title }}</a></h2>
    <h3> {{step.title}}</h3>
    {{ step.content|linebreaks }}
</article>
{% endblock content%}

templates/home.html
{% extends "layout.html"%}
{% block title%} Django App 2 Home{% endblock title%}
{% block content%}
<h1>Welcome</h1>
{% endblock content%}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock title %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    </head>
    <body>
    <div class="site-container">
        <nav>
            
            <a href="{% url 'courses:list' %}">Courses<a>
        </nav>
        {% block content%} {% endblock content%}</div></body>
</html>